# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scaler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scaler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscaler.proto\x12\x0e\x65xternalscaler\"2\n\x0fScaledObjectRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"\"\n\x10IsActiveResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"4\n\nMetricSpec\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x12\n\ntargetSize\x18\x02 \x01(\x03\"H\n\x15GetMetricSpecResponse\x12/\n\x0bmetricSpecs\x18\x01 \x03(\x0b\x32\x1a.externalscaler.MetricSpec\"6\n\x0bMetricValue\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\x13\n\x0bmetricValue\x18\x02 \x01(\x03\"M\n\x11GetMetricsRequest\x12\x38\n\x0fscaledObjectRef\x18\x01 \x01(\x0b\x32\x1f.externalscaler.ScaledObjectRef\"G\n\x12GetMetricsResponse\x12\x31\n\x0cmetricValues\x18\x01 \x03(\x0b\x32\x1b.externalscaler.MetricValue2\x93\x02\n\x0e\x45xternalScaler\x12O\n\x08IsActive\x12\x1f.externalscaler.ScaledObjectRef\x1a .externalscaler.IsActiveResponse\"\x00\x12Y\n\rGetMetricSpec\x12\x1f.externalscaler.ScaledObjectRef\x1a%.externalscaler.GetMetricSpecResponse\"\x00\x12U\n\nGetMetrics\x12!.externalscaler.GetMetricsRequest\x1a\".externalscaler.GetMetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scaler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALEDOBJECTREF']._serialized_start=32
  _globals['_SCALEDOBJECTREF']._serialized_end=82
  _globals['_ISACTIVERESPONSE']._serialized_start=84
  _globals['_ISACTIVERESPONSE']._serialized_end=118
  _globals['_METRICSPEC']._serialized_start=120
  _globals['_METRICSPEC']._serialized_end=172
  _globals['_GETMETRICSPECRESPONSE']._serialized_start=174
  _globals['_GETMETRICSPECRESPONSE']._serialized_end=246
  _globals['_METRICVALUE']._serialized_start=248
  _globals['_METRICVALUE']._serialized_end=302
  _globals['_GETMETRICSREQUEST']._serialized_start=304
  _globals['_GETMETRICSREQUEST']._serialized_end=381
  _globals['_GETMETRICSRESPONSE']._serialized_start=383
  _globals['_GETMETRICSRESPONSE']._serialized_end=454
  _globals['_EXTERNALSCALER']._serialized_start=457
  _globals['_EXTERNALSCALER']._serialized_end=732
# @@protoc_insertion_point(module_scope)
