apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: nginx-app
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10  
  cooldownPeriod: 30   
  triggers:
    - type: external
      metadata:
        scalerAddress: "external-scaler.default.svc.cluster.local:80"
        metricName: "onpremise-app-health"
        targetValue: "1"
